package cms

import "github.com/denverdino/aliyungo/common"

/**
	Auto generated by aliyun-ecosphere / golang-sdk-gen
	zhongwei.lzw@alibaba-inc.com
	2017/10/26
**/

/**
	CreateAlarm Action
**/
type CreateAlarmRequest struct {
	Name               string
	Namespace          string
	MetricName         string
	Dimensions         string
	Period             int32
	Statistics         string
	ComparisonOperator string
	Threshold          string
	EvaluationCount    int32
	ContactGroups      string
	StartTime          int32
	EndTime            int32
	SilenceTime        int32
	NotifyType         int32
}

type CreateAlarmResponse struct {
	Response
	Data string
}

func (client *CmsClient) CreateAlarm(req CreateAlarmRequest) (CreateAlarmResponse, error) {
	var resp CreateAlarmResponse
	err := client.InvokeWithMethod(common.POSTRequestMethod, "CreateAlarm", req, &resp)
	if err != nil {
		return CreateAlarmResponse{}, err
	}
	return resp, nil
}

/**
	DeleteAlarm Action
**/
type DeleteAlarmRequest struct {
	Id string
}

type DeleteAlarmResponse struct {
	Response
}

func (client *CmsClient) DeleteAlarm(req DeleteAlarmRequest) (DeleteAlarmResponse, error) {
	var resp DeleteAlarmResponse
	err := client.Invoke("DeleteAlarm", req, &resp)
	if err != nil {
		return DeleteAlarmResponse{}, err
	}
	return resp, nil
}

/**
	DisableAlarm Action
**/

type DisableAlarmRequest struct {
	Id string
}

type DisableAlarmResponse struct {
	Response
}

func (client *CmsClient) DisableAlarm(req DisableAlarmRequest) (DisableAlarmResponse, error) {
	var resp DisableAlarmResponse
	err := client.Invoke("DisableAlarm", req, &resp)
	if err != nil {
		return DisableAlarmResponse{}, err
	}
	return resp, nil
}

/**
	EnableAlarm Action
**/

type EnableAlarmRequest struct {
	Id string
}

type EnableAlarmResponse struct {
	Response
}

func (client *CmsClient) EnableAlarm(req EnableAlarmRequest) (EnableAlarmResponse, error) {
	var resp EnableAlarmResponse
	err := client.Invoke("EnableAlarm", req, &resp)
	if err != nil {
		return EnableAlarmResponse{}, err
	}
	return resp, nil
}

/**
ListAlarm Action
*/

type ListAlarmRequest struct {
	Id         string
	Namespace  string
	Name       string
	Dimension  string
	State      string
	IsEnable   bool
	PageNumber int32
	PageSize   int32
}

type AlarmMember struct {
	Id                 string
	Name               string
	Namespace          string
	MetricName         string
	Dimensions         string
	Period             int32
	Statistics         string
	ComparisonOperator string
	Threshold          string
	EvaluationCount    int32
	StartTime          int32
	EndTime            int32
	SilenceTime        int32
	NotifyType         int32
	Enable             bool
	State              string
	ContactGroups      string
}

type ListAlarmResponse struct {
	Response
	NextToken int32
	Total     int32
	AlarmList struct {
		Alarm []AlarmMember
	}
}

func (client *CmsClient) ListAlarm(req ListAlarmRequest) (ListAlarmResponse, error) {
	var resp ListAlarmResponse
	err := client.Invoke("ListAlarm", req, &resp)
	if err != nil {
		return ListAlarmResponse{}, err
	}
	return resp, nil
}
